version: '3'

services:
  dynamodb:
    build: ./docker/dynamodb
    container_name: dynamo-dynamodb
    environment:
      TZ: Asia/Tokyo
    ports:
      - 8000:8000
    command: -jar DynamoDBLocal.jar -dbPath /home/dynamodblocal/data 
    volumes:
      - ./docker/dynamodb/bin:/home/dynamodblocal/data
