version: '3'

services:
  dynamodb:
    build: ./docker/dynamodb
    container_name: dynamo-dynamodb
    environment:
      TZ: Asia/Tokyo
    ports:
      - 8000:8000
    volumes:
      - ./docker/dynamodb/bin:/data
